In [1]:
import numpy as np

In [2]:
X = np.array([1, 2, 3])
print(X)
print(type(X))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
lis = [5, 4, -10]
X = np.asarray(lis)
print(X)
print(type(X))

[  5   4 -10]
<class 'numpy.ndarray'>


In [4]:
X = np.asarray(lis, float)
print(X)
print(X.dtype)

[  5.   4. -10.]
float64


In [5]:
X.shape

(3,)

In [6]:
np.array?

In [7]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X.shape)

(2, 3)


In [8]:
X[0, 0]

np.int64(1)

In [9]:
X[0]

array([1, 2, 3])

In [10]:
print(X[0, 0])

1


In [11]:
X[0][0]

np.int64(1)

In [12]:
X[0, :]

array([1, 2, 3])

In [14]:
X = np.zeros((4, 5))
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.random? # [0.0, 1.0)

In [18]:
X = np.random.random((4, 5))
X

array([[0.94668423, 0.98978264, 0.03770776, 0.77858322, 0.59413554],
       [0.96184328, 0.96159727, 0.60510503, 0.59560221, 0.21457301],
       [0.81157605, 0.54514121, 0.53304692, 0.97994174, 0.35626742],
       [0.16405729, 0.34581741, 0.17731982, 0.35222713, 0.19559329]])

In [19]:
Z = X.T

In [20]:
print(Z)

[[0.94668423 0.96184328 0.81157605 0.16405729]
 [0.98978264 0.96159727 0.54514121 0.34581741]
 [0.03770776 0.60510503 0.53304692 0.17731982]
 [0.77858322 0.59560221 0.97994174 0.35222713]
 [0.59413554 0.21457301 0.35626742 0.19559329]]


In [21]:
Y = X.reshape(20, 1)
Y

array([[0.94668423],
       [0.98978264],
       [0.03770776],
       [0.77858322],
       [0.59413554],
       [0.96184328],
       [0.96159727],
       [0.60510503],
       [0.59560221],
       [0.21457301],
       [0.81157605],
       [0.54514121],
       [0.53304692],
       [0.97994174],
       [0.35626742],
       [0.16405729],
       [0.34581741],
       [0.17731982],
       [0.35222713],
       [0.19559329]])

In [22]:
Y = X.reshape(-1, 20)
Y

array([[0.94668423, 0.98978264, 0.03770776, 0.77858322, 0.59413554,
        0.96184328, 0.96159727, 0.60510503, 0.59560221, 0.21457301,
        0.81157605, 0.54514121, 0.53304692, 0.97994174, 0.35626742,
        0.16405729, 0.34581741, 0.17731982, 0.35222713, 0.19559329]])

In [23]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
B = np.arange(10)
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
A * B # point wise operation

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
A + 1  # concept of broad casting

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
A = np.random.random((2, 3))
print(A)
print()
print(A + 1)

[[0.16521249 0.56164987 0.23770874]
 [0.41815771 0.18808922 0.48798648]]

[[1.16521249 1.56164987 1.23770874]
 [1.41815771 1.18808922 1.48798648]]


In [34]:
random = np.random.random((2, 3)) * 10
print(random)
A = np.floor(random)
print(A)

[[4.1247862  1.15048283 0.56912699]
 [1.55875168 4.29658276 6.86745119]]
[[4. 1. 0.]
 [1. 4. 6.]]


In [35]:
u = [1, 2, 3]
v = [-1, 0, 1]

p1 = np.inner(u, v)
p1

np.int64(2)

In [36]:
p2 = np.outer(u, v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [37]:
A = np.ones((2, 3))
print(A)
B = np.ones((3, 2))
print(B)

np.dot(A, B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.]])

In [38]:
np.dot(B.T, A.T)

array([[3., 3.],
       [3., 3.]])

In [40]:
A = np.ones((2, 3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
A.sum()

np.float64(6.0)

In [43]:
# A.shape (2, 3)
print(A.sum(axis=0))
print(A.sum(axis=0, keepdims=True))

[2. 2. 2.]
[[2. 2. 2.]]


In [44]:
print(A.sum(axis=1))
print(A.sum(axis=1, keepdims=True))

[3. 3.]
[[3.]
 [3.]]


In [45]:
A.max()

np.float64(1.0)